name: Robot Framework Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          robot --variable BROWSER:headlesschrome --outputdir output tests/

      - name: Upload Robot Framework Report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: output/
